import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
//import styles from '@/styles/Home.module.css'
      // pages/index.js
import React, { useState } from 'react';
import TaskForm from '../components/TaskForm';
import TaskList from '../components/TaskList';
import Boton from '@/components/buttons/login';

const inter = Inter({ subsets: ['latin'] })

const HomePage = () => {
  const [tasks, setTasks] = useState([]);

  const addTask = title => {
    const newTask = {
      id: Date.now(),
      title
    };
    setTasks([...tasks, newTask]);
  };

  const deleteTask = id => {
    const updatedTasks = tasks.filter(task => task.id !== id);
    setTasks(updatedTasks);
  };

    <Head>
      <title>Task List</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head> 
  return (
    <div>
      <Boton />
      <h1>Lista de Tareas</h1>
      <TaskForm addTask={addTask} />
      <TaskList tasks={tasks} deleteTask={deleteTask} />
    </div>
  );
};

export default HomePage;

