
import Boton from "@/components/buttons/loginBtn"
import Barra from "@/components/navBar/barra.js"
import React, { useState } from 'react';
import Head from "next/head";
import Footer from "@/components/footer/footer"
import SocialLogin from "@/components/login/SocialLogin";

//import React from 'react';
import ReactDOM from 'react-dom';
//import Ingresar from "@/components/login/login";
import LoginAi from "@/components/login/LoginAi";
import LoginButton from "@/components/buttons/loginBtn";
import Parrafo from "@/components/ParrafoRelleno";



export default function Test() {       
    return(
        <>
<Head>
<title>Task List</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
  integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
  crossorigin="anonymous"
/>
</Head>
       <div>
 <Barra></Barra>
        </div>
       
        <Parrafo></Parrafo>

        <SocialLogin></SocialLogin>
        
        {/* <LoginAi></LoginAi> */}
        {/* <LoginButton></LoginButton> */}
  


        <Footer></Footer>
        </>
    )
}