
import Boton from "@/components/buttons/login"
import Barra from "@/components/navBar/barra.js"
import React, { useState } from 'react';
import Head from "next/head";
import Footer from "@/components/footer/footer";
import SocialLogin from "@/components/login/SocialLogin";

//import React from 'react';
import ReactDOM from 'react-dom';
//import Ingresar from "@/components/login/login";
import LoginAi from "@/components/login/LoginAi";



export default function Test() {       
    return(
        <>
<Head>
<title>Task List</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
  integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
  crossorigin="anonymous"
/>
</Head>
       <div>
 <Barra></Barra>
        </div>
        <br></br>
        <p>hola esto es texto</p><br></br>
        <SocialLogin></SocialLogin>

        
        <LoginAi></LoginAi>
  
);

        <Footer></Footer>
        </>
    )
}